### ISSUE TITLE
[MVM] Huntsman bugs

### ISSUE THREAD

**Issue by DrCactusTF2** [mastercomfig/team-comtress-2#255]
The huntsman has a few notable bugs in Mann vs. Machine.

1. Damage is improperly rounded.
    412 / 360 = 1,1444 = 14,44% <---- first Damage Upgrade
    465 / 360 = 1,2916 = 29,16% <---- second Damage Upgrade
    517 / 360 = 1,4361 = 43,61% <---- third Damage Upgrade
    570 / 360 = 1,5833 = 58,33% <---- fourth Damage Upgrade
    Max damage upgrade huntsman only increases the damage by 58.33% instead of the advertised 100%
2. Reload stability arc
    Reload speed decreases the charge time needed to reach the max damage, but the arrow stability you get at max charge is unaffected, and you still need to wait for the stock huntsman charge time to get stable arrows
3. Penetration is completely broken on Huntsman
    Huntsman actually suffers from buying projectile penetration, as penetration will cause the arrows to instantly break if you tap fire them, or fire them while ubered.
    Pyro bots also cannot reflect non-penetration arrows, but can reflect penetration arrows just fine

### Checklist
- [x] None of the open *or* closed issues document this problem.
- [x] This is a bug, not a new idea.
- [x] This is objectively a bug, and not something that people commonly disagree on.
- [x] This bug is in the code of the game, not in the textures, sounds, or other resources.
- [x] This issue occurs on the latest vanilla TF2 update.
- [ ] This issue is listed on the [Source 1 official bugtracker](https://github.com/ValveSoftware/Source-1-Games/issues).
- [ ] This issue occurs with DirectX level 100.
- [x] This issue occurs on the latest Team Comtress release, or the `master` branch.
- [x] This issue occurs when using no custom content.
- [x] This issue occurs when using `start_tf2.bat` (or `start_server.bat`) with no custom launch options.
- [x] This issue occurs when using a listen server (using the `map` command ingame).
- [x] This issue occurs when using a dedicated server.
- [ ] This bug is in the internal procedures or tooling (e.g. the build process).

### Reproduction
The steps to recreate the bug.
Bugs that cannot be recreated are extremely unlikely to receive a fix
1. Buy damage upgrades, and use them on robot or tank
2. buy reload speed and compare them with vanilla huntsman speeds
3. Buy penetration and spam M1, or fire a non penetration arrow, and then a penetration arrow at a hard level pyro bot

### Screenshots
https://steamuserimages-a.akamaihd.net/ugc/39725818316806181/43E60E6B891963DF6DB4A8F780AD3F98904AF9C7/
Max damage crit huntsman with full charge vs. tank

**Comment by Yttrium-tYcLief** [comment]
>Damage is improperly rounded

Have you confirmed this in TC2? We've fixed numerous damage rounding errors, and have mostly fixed all of the MvM issues relating to it (especially the minigun).

>or fire them while ubered

Is this really as blatant as it sounds? An ubered Sniper's arrows will not penetrate, regardless of upgrades?

**Comment by DrCactusTF2** [comment]
> 
> 
> > Damage is improperly rounded
> 
> Have you confirmed this in TC2? We've fixed numerous damage rounding errors, and have mostly fixed all of the MvM issues relating to it (especially the minigun). As far as this goes, it sounds like the Huntsman only receives a +15% damage buff, not a +25%. Maybe someone with code smarts could look over that upgrade.
> 
> > or fire them while ubered
> 
> Is this really as blatant as it sounds? An ubered Sniper's arrows will not penetrate, regardless of upgrades?

Yes, I tested all issues in TC2 and they are still present.
The problem is not that an ubered snipers arrows do not penetrate, but that when a sniper is ubered and he has penetration, the arrow will just break inside the sniper's body and never fire it. I am uploading a video to demonstrate these issues

**Comment by DrCactusTF2** [comment]
https://youtu.be/7zJNvv1eE48
tested on the latest TC2 release.
Only need to watch up to 1:09 as that shows the uber penetration bug, and the improperly rounded +25% damage bonus

**Comment by Yttrium-tYcLief** [comment]
Can confirm ingame. Also affects Rescue Ranger and Crusader's Crossbow. Doesn't happen when walking backwards.
